### ISSUE TITLE
transcription.txt and example.ctm format

### ISSUE THREAD

**Issue by 1215thebqtic** [Marvin84/word_graph#1]
Hi,

what is the format of the input files transcription.txt and example.ctm? Could you please upload example files? Thank you very much!

**Comment by Marvin84** [comment]
Hi,
yes of course. I just uploaded them.
Regards

**Comment by Marvin84** [comment]
> Hi,
> 
> what is the format of the input files transcription.txt and example.ctm? Could you please upload example files? Thank you very much!


Hi,
yes of course. I just uploaded them.
Regards
